baseURL = 'https://rainbow-dango-397e43.netlify.app/'
languageCode = 'es-ar'
defaultContentLanguage = 'es'
title = 'ET12'
ordersectionsby = 'weight'

[module]
[[module.imports]]
  path = 'github.com/McShelby/hugo-theme-relearn'

[params]
  themeVariant = ['auto','Claro','Oscuro']
  collapsibleMenu = true
  images=['/imgs/et12.svg']

[outputs]
  home = ["HTML", "RSS", "SEARCH", "SEARCHPAGE"]

[[menu.shortcuts]]
name = "<i class='fa-solid fa-microphone-lines'></i> Nuestra Radio"
url = "https://www.tec12radio.com/"
weight = 10

[[menu.shortcuts]]
name = "<i class='fab fa-brands fa-facebook'></i> Facebook"
url = "https://www.facebook.com/jose.desanmartin.927"
weight = 11

[[menu.shortcuts]]
name = "<i class='fab fa-brands fa-instagram'></i> Instagram"
url = "https://www.instagram.com/escuelatec12/"
weight = 12

[[menu.shortcuts]]
name = "<i class='fab fa-brands fa-github'></i> GitHub repo"
identifier = "ds"
url = "https://github.com/et12webmaster/et12webmaster.github.io"
weight = 13

[[menu.shortcuts]]
name = "<i class='fa-solid fa-folder-open'></i> Changelog"
url = "/changelog.md"
weight = 14

[[menu.shortcuts]]
name = "<i class='fas fa-tags'></i> Tags"
url = "/tags"
taxonomies = ["tag"]

[markup.goldmark.renderer]
unsafe = true
