baseURL = 'https://et12.edu.ar/'
languageCode = 'en-us'
defaultContentLanguage = 'es'
title = 'ET12'

[module]
[[module.imports]]
  path = 'github.com/McShelby/hugo-theme-relearn'



[params]
  themeVariant = [ "relearn-light", "relearn-dark", 'Oficial', 'Argentina', 'Oficial-Oscuro','Oficial-Claro']

[[menu.shortcuts]]
name = "<i class='fab fa-brands fa-github'></i> GitHub repo"
identifier = "ds"
url = "https://github.com/et12webmaster/et12webmaster.github.io"
weight = 10

[[menu.shortcuts]]
name = "<i class='fab fa-brands fa-facebook'></i> Facebook"
url = "https://www.facebook.com/jose.desanmartin.927"
weight = 11

[[menu.shortcuts]]
name = "<i class='fab fa-brands fa-instagram'></i> Instagram"
identifier = "hugodoc"
url = "https://www.instagram.com/escuelatec12/"
weight = 20

[[menu.shortcuts]]
name = "changelog"
url = "/changelog.md"
weight = 20